### ISSUE TITLE
python manage.py airports import not working

### ISSUE THREAD

**Issue by ThunderTrent** [bashu/django-airports#12]
django.core.exceptions.FieldError: Cannot resolve keyword 'city' into field. Choices are: airport, alt_names, area, capital, cities, code, code3, continent, continent_id, currency, currency_name, currency_symbol, id, language_codes, name, neighbours, phone, population, postal_code_format, postal_code_regex, postal_codes, regions, slug, tld

Django-cities is installed, using django 1.8

**Comment by eracle** [comment]
Hello @ThunderTrent 
Thanks for the ticket!
That was was because latest version of django-cities changed its API, so the field city is not longer available on the Country model. 
I fixed it on latest PR. @bashu shall we close this?
Not tried with django 1.8, but now with django 2.0 works.
