### ISSUE TITLE
New logo for Airports

### ISSUE THREAD

**Issue by reallinfo** [bashu/django-airports#19]
Hello, I designed logo for airports. If you like it, I will send you a pr and files.

Also, If there's anything you want, I can design it.

![django-airports](https://user-images.githubusercontent.com/36298335/39084765-aeac9fa8-4582-11e8-8393-79cf959823f2.jpg)

**Comment by bashu** [comment]
![36909043-e1f2c704-1e34-11e8-84d7-b3119091cb2c](https://user-images.githubusercontent.com/144783/39084835-f60ec642-45a4-11e8-8075-15fc9c6dce16.gif)

@reallinfo what about PNG instead of JPG?

**Comment by reallinfo** [comment]
yeah, I sent a pr. Please check :) https://github.com/bashu/django-airports/pull/20

I am glad you like it. Btw, this .gif is very good :)

Here are the all files.

https://drive.google.com/open?id=1P1TTg5AV1YqO1kypP7EmKhNSKFhAR44L

**Comment by bashu** [comment]
@reallinfo thanks a lot! feel free to include yourself in AUTHORS.rst

**Comment by reallinfo** [comment]
Thanks!
