### ISSUE TITLE
Can't find city for TYS airport

### ISSUE THREAD

**Issue by YPCrumble** [bashu/django-airports#22]
* django-airports version: development branch
* Django version: 2.0.6
* Python version: 3.6.2
* Operating System: Mac OSX

### Description

Thanks for building this library! I was trying to install it and test a random airport (I chose Knoxville, TN, iata code TYS) to see if it linked the correct city to the airport.

### What I Did

I installed the package, ran `python manage.py airports` and everything downloaded fine.

However, the city (Knoxville) isn't on the TYS airport (city is null for this airport). 

I checked over at openflights.org and in the [airports.dat](https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat) file it correctly shows Knoxville as the city:

    3676,"McGhee Tyson Airport","Knoxville","United States","TYS","KTYS",35.81100082,-83.9940033,981,-5,"A","America/New_York","airport","OurAirports"

Is this user error, or is there another reason this wouldn't have picked up the correct city for this airport? It looks like this doesn't pull directly from airports.dat but I'm not sure how I could troubleshoot. Any help would be greatly appreciated! I'm working on a site that uses airport distances and would be happy to contribute to this library if I end up using it!

**Comment by eracle** [comment]
Dear @YPCrumble, have you tried with my un-merged branch?
https://github.com/bashu/django-airports/pull/18
Regards

**Comment by eracle** [comment]
Dear @YPCrumble, 
@vlinhart just fixed a bug related with latitude and longitude of the represented points in GeoDjango, could you please try latest PR we did? https://github.com/bashu/django-airports/pull/18

**Comment by vlinhart** [comment]
Yep I can confirm that I have city ` Knoxville slug id 4634946-Knoxville` for this airport after the import using the PR branch.

**Comment by eracle** [comment]
Ok, so I think we could close this issue. @bashu

**Comment by bashu** [comment]
Yes, can confirm

![Screenshot 2021-12-16 at 19 37 38](https://user-images.githubusercontent.com/144783/146373556-02b32f3a-0807-4f60-935b-44c631d5abd3.png)
