### ISSUE TITLE
May I partecipate as mantainer?

### ISSUE THREAD

**Issue by eracle** [bashu/django-airports#23]
Hello there!
I have seen that @bashu was unresponsive during last period, and especially about latest PR https://github.com/bashu/django-airports/pull/18 where @vlinhart contributed.

I understand we are on holidays, but in order to take off some load from @bashu, may I ask to became a maintainer of the project? I don't want to create my own fork, I would rather prefer contributing and create a community over this project.
Regards

**Comment by vlinhart** [comment]
:+1:

**Comment by bashu** [comment]
to @eracle still interested?

**Comment by eracle** [comment]
Many years have passed. I am not on Airplanes anymore :-)

**Comment by eracle** [comment]
Many years have passed. I am not on Airplanes anymore :-)

**Comment by bashu** [comment]
hiking 4 life
