### ISSUE TITLE
Latest version not pushed to PyPi?

### ISSUE THREAD

**Issue by LiamK** [bashu/django-airports#24]
* django-airports version: django-airports==0.1.4
* Django version: 2.1
* Python version: 3.6.3
* Operating System: Ubuntu 17.10

### Description

Installed django-airports via PyPi.

### What I Did

Tried to migrate using

```
python manage.py migrate airports
```
Exceptions due to missing on_delete field in airports/models.py and airports/migrations/0001_initial.py
I worked around it by fixing the errors myself.
Later, I looked at the code here on github and it looks like those errors have already been fixed.
It looks like the latest version has not been pushed to PyPi.

**Comment by LiamK** [comment]
Oh, I see I must have gotten the master branch from PyPi. 
Now I'm using the develop branch and it's working.

**Comment by bashu** [comment]
airport v0.2 is already on PyPi, version 1.0 will be released later this week
