### ISSUE TITLE
Forked and changed data source

### ISSUE THREAD

**Issue by LiamK** [bashu/django-airports#25]
I have forked django-airports and made quite a few changes.
The main one is that I changed the data source to ourairports.org. They seem to have a more complete collection of airports.
I have this working, although I'm continuing to make changes, so I'm not ready to make a pull request.
I'm wondering if you would want to incorporate what I've done, or not.

Incidentally, I was also able to speed up the import process by adding regions (states, provinces, etc.).  That allows a more precise location of a city, as well as limiting the query set when doing distance calculations.
I was able to find nearest cities for 94% of airports.
There are 55,041 airports (that's including heliports).

**Comment by bashu** [comment]
@LiamK https://youtu.be/wQZiF7PSsck?t=5

**Comment by bashu** [comment]
to @LiamK thank you
